#!/usr/bin/env bash
# Check new instance for smctm repository

INSTANCE_IP="142.170.89.112"
INSTANCE_PORT="62162"

echo "🔍 Checking New Instance"
echo "========================"
echo "Instance: $INSTANCE_IP:$INSTANCE_PORT"
echo ""
echo "📝 SSH Command:"
echo "   ssh -i ~/.ssh/vastai root@$INSTANCE_IP -p $INSTANCE_PORT -L 8080:localhost:8080"
echo ""
echo "Once connected, run these commands:"
echo ""
echo "   # Check /workspace"
echo "   ls -la /workspace/"
echo ""
echo "   # Check if smctm exists"
echo "   ls -la /workspace/smctm/ 2>/dev/null && echo '✅ smctm EXISTS!' || echo '❌ smctm NOT FOUND'"
echo ""
echo "   # Check onstart log"
echo "   cat /var/log/onstart.log | tail -30"
echo ""
echo "   # If not found, manually clone:"
echo "   cd /workspace"
echo "   export GIT_TERMINAL_PROMPT=0"
echo "   export GIT_ASKPASS=/bin/echo"
echo "   export GITHUB_PAT=\"\${GITHUB_PAT:-your_github_token_here}\""
echo "   GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/echo git clone \"https://\${GITHUB_PAT}@github.com/almaghrabima/smctm.git\" smctm < /dev/null"
echo ""
