#!/usr/bin/env bash
# Script to fix current Vast.ai instance - install tmux and check for smctm

INSTANCE_IP="136.59.129.136"
INSTANCE_PORT="34913"
SSH_KEY="$HOME/.ssh/vastai"

echo "🔧 Fixing Current Vast.ai Instance"
echo "==================================="
echo "Instance: $INSTANCE_IP:$INSTANCE_PORT"
echo ""

echo "📝 Manual Steps:"
echo ""
echo "1. Connect via SSH:"
echo "   ssh -i $SSH_KEY root@$INSTANCE_IP -p $INSTANCE_PORT"
echo ""
echo "2. Once connected (you may see tmux errors, that's OK), run these commands:"
echo ""
echo "   # Install tmux"
echo "   apt-get update && apt-get install -y tmux"
echo ""
echo "   # Disable tmux auto-start"
echo "   touch ~/.no_auto_tmux"
echo ""
echo "   # Check for smctm"
echo "   ls -la /workspace/"
echo "   ls -la /workspace/smctm/"
echo ""
echo "   # If smctm doesn't exist, clone it:"
echo "   cd /workspace"
echo "   GIT_TERMINAL_PROMPT=0 git clone https://\${GITHUB_PAT}@github.com/almaghrabima/smctm.git"
echo ""
echo "3. Disconnect and reconnect - tmux should work now"
echo ""
